### ISSUE TITLE
Control and speed up pygame frame rate

### ISSUE THREAD

**Issue by samuelleach** [DanielSlater/PyGamePlayer#3]
Hi Daniel - we talked briefly at pydata last week.

I've got your deep q pong player running on a 4 core Macbook pro.
- Can the clock speed / frame rate of pygame be increased? I am new to this package.

A quick back of the envelope calculation shows that about 20 hours game play is needed before the 500000 observation steps will be completed and training starts. I'm wondering how the wall clock time can be reduced.

By the way, pygame itself has a few dependencies which I managed to install using

`brew install sdl`
`brew install sdl_ttf`

**Comment by DanielSlater** [comment]
Hi Samuel, I remember talking to you, thanks for getting in touch. 

PyGame will normally run at as high fps as it can. There is an init parameter on the PyGamePlayer class called force_game_fps. This means even if the game is running at 40 fps the internal clock will be hacked so it seems to the agent that the game is running at what ever frame rate you put in. So if you decrease this number the game will effectively run faster, though if the number is too low the game will appear to choppy to the agent to learn effectively. 

The 500000 observations number was taken from the deepmind paper but I think they wanted it very high to get the best range of data to train on(they say it took about 4 days to train so your figures seem accurate). When testing it I normally put the number down much lower, say 3000 and the same for the explore steps. Also yeah it would be great if the whole thing would run faster, I wonder if there is anything I can do around hacking pygame to skip the screen buffer when training or something like that.

Thanks for pointing out the dependencies I've not got a mac so haven't tried it myself, I'll update the docs to include those dependencies.

**Comment by DanielSlater** [comment]
Actually forgot the other big improvement that can be made to the speed that I really should do at some point, is that the deep_q_agent because it was originaly set up for Atari with fixed frame rate and so only makes decisions every 4th frame. Given here we can control how fast the game runs we can just reduce the frame rate by 4 and change the code to make decisions every frame to give a 4x increase in speed. I will try and do this some time soon(though also feel free to try yourself and make a push if you want).

**Comment by samuelleach** [comment]
Ok, thanks for the pointers. I'll try out the technique you mention above with the frame rate and frames per action.
