### ISSUE TITLE
is append working right here?

### ISSUE THREAD

**Issue by flobotics** [DanielSlater/PyGamePlayer#6]
hi,
when i look at line 100 at  https://github.com/DanielSlater/PyGamePlayer/blob/master/examples/deep_q_pong_player.py#L100 i see
- current_state = np.append(self._last_state[:, :, 1:], screen_resized_binary, axis=2)

when i use this test code:

```

import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print a.shape
print a
b = np.stack(tuple(a for _ in range(4)), axis=2)
print b.shape
print b
c = np.array([[7,8,9], [10,11,12]])
print c.shape
print c
d = np.reshape(c, (2,3,1))
print d.shape
e = np.append(b[:,:,1:], d, axis=2)
print e.shape
print e
f = np.array([[13,14,15],[16,17,18]])
g = np.reshape(f, (2,3,1))
h = np.append(b[:,:,1:], g, axis=2)
print h.shape
print h
```

it prints:

```

(2, 3)
[[1 2 3]
 [4 5 6]]
(2, 3, 4)
[[[1 1 1 1]
  [2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]
  [6 6 6 6]]]
(2, 3)
[[ 7  8  9]
 [10 11 12]]
(2, 3, 1)
(2, 3, 4)
[[[ 1  1  1  7]
  [ 2  2  2  8]
  [ 3  3  3  9]]

 [[ 4  4  4 10]
  [ 5  5  5 11]
  [ 6  6  6 12]]]
(2, 3, 4)
[[[ 1  1  1 13]
  [ 2  2  2 14]
  [ 3  3  3 15]]

 [[ 4  4  4 16]
  [ 5  5  5 17]
  [ 6  6  6 18]]]

```

but should it not be shifted-like inserted, so that the old values (frames) will all get lost after time ? or do i think wrong ?

**Comment by flobotics** [comment]
i am sorry, my code is wrong, this si more correct

```
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print a.shape
print a
b = np.stack(tuple(a for _ in range(4)), axis=2)
print b.shape
print b
c = np.array([[7,8,9], [10,11,12]])
print c.shape
print c
d = np.reshape(c, (2,3,1))
print d.shape
e = np.append(b[:,:,1:], d, axis=2)
print e.shape
print e
f = np.array([[13,14,15],[16,17,18]])
g = np.reshape(f, (2,3,1))
h = np.append(e[:,:,1:], g, axis=2)
print h.shape
print h
```

**Comment by DanielSlater** [comment]
Hi Flo, Sorry just to check it's OK in it's current form?(I very much hope so)

**Comment by flobotics** [comment]
hi @DanielSlater 
sorry for stress. i hope it will also work with my code :)

**Comment by DanielSlater** [comment]
No problem, glad your finding it useful :) if you do find bugs, very happy for you to tell me so I can fix them.

**Comment by flobotics** [comment]
very useful, thanks alot
i dont think so, but if i find one, i will send issue to you

**Comment by flobotics** [comment]
hi @DanielSlater ,
i just wanna ask, how do you extract the data from self._observations ? you do it on line 152  https://github.com/DanielSlater/PyGamePlayer/blob/master/examples/deep_q_pong_player.py#L152
but when i try to do it the same way like you, i get the error:

`TypeError: tuple indices must be integers, not list`

i searched alot on web but cannot find anything that helps me, perhaps you could help me

my line of code is here, line 317
https://github.com/flobotics/flobotics_tensorflow_controller/blob/master/nodes/listener.py#L317

**Comment by DanielSlater** [comment]
Hi @flobotics 
So the problem you have here is that in your code the line 
OBS_LAST_STATE_INDEX = range(5)

Give you a tuple, contrast that with the line in PyGamePlayer

OBS_LAST_STATE_INDEX, OBS_ACTION_INDEX, OBS_REWARD_INDEX, OBS_CURRENT_STATE_INDEX, OBS_TERMINAL_INDEX = range(5)

In PyGamePlayer because of python unpacking OBS_LAST_STATE_INDEX will be an int. In your version it will be a tuple(the number 1 through 5).

Hope this helps

**Comment by flobotics** [comment]
aaahh, got it, after days :)  thank you
