### ISSUE TITLE
Strange bug, moving from DOWN to UP

### ISSUE THREAD

**Issue by thibo73800** [DanielSlater/PyGamePlayer#8]
Hi, 

First, I would like to thanks you about your job and yours tutorials about Q learning method with tensorflow. I learn lots of things thanks to you !

I would like to report a bug. I prepared a little code to show you what happening. Maybe I did something wrong, but according to me, this is a normal behavior which should work. 

`class PongPlayer(PyGamePlayer):
    def **init**(self, force_game_fps=60, run_real_time=False):
        """
        Example class for playing Pong
        """
        super(PongPlayer, self).**init**(force_game_fps=force_game_fps, run_real_time=run_real_time)
        self.last_bar1_score = 0.0
        self.last_bar2_score = 0.0
        self.it = 0

```
def get_keys_pressed(self, screen_array, feedback, terminal):
    # TODO: put an actual learning agent here
    self.it += 1
    if self.it < 100:  
        print "K_DWON"
        return [K_DOWN]
    else:
        print "K_UP"
        return [K_UP]`
```

When I execute this code, the agent going down, but when a new action is returned (K_UP), the agent stops working and don't move anymore. Even If continue to return K_UP.
Here, I made a simple example, but this cause lot of problems when I try to launch my real code.

Here, a gif showing the problem.

<img width=500 src="https://cloud.githubusercontent.com/assets/4882542/18614922/e6ef85f0-7d98-11e6-9f25-2a51ecfedf10.gif" />

Thanks you for your help !

**Comment by DanielSlater** [comment]
Thanks for fixing @thibo73800
